# SPDX-FileCopyrightText: Copyright © 2026 Caleb Cushing
#
# SPDX-License-Identifier: CC0-1.0

---
exclude: '^\.git/'
repos:
  - repo: local
    hooks:
      - id: prettier
        name: Prettier
        entry: yarn prettier --cache --ignore-unknown --write
        language: system
        types: [text]
        stages: [pre-commit]

      - id: shfmt
        name: shfmt
        entry: shfmt --write
        language: system
        files: '(\.config/git/hooks/.*|.*\.sh)$'
        stages: [pre-commit]

      - id: reuse-config
        name: REUSE annotate config files
        entry: uv run --frozen --group dev reuse annotate
        args:
          - --copyright
          - "Caleb Cushing"
          - --merge-copyrights
          - --copyright-prefix
          - spdx-string-symbol
          - --license
          - "CC0-1.0"
          - --fallback-dot-license
        language: system
        files: '^(?!package\.json$).+\.json$'
        stages: [pre-commit]

      - id: reuse-package-json
        name: REUSE annotate package.json
        entry: uv run --frozen --group dev reuse annotate
        args:
          - --copyright
          - "Caleb Cushing"
          - --merge-copyrights
          - --copyright-prefix
          - spdx-string-symbol
          - --license
          - "MIT"
          - --fallback-dot-license
        language: system
        files: '^package\.json$'
        stages: [pre-commit]

      - id: reuse-docs
        name: REUSE annotate docs
        entry: uv run --frozen --group dev reuse annotate
        args:
          - --copyright
          - "Caleb Cushing"
          - --merge-copyrights
          - --copyright-prefix
          - spdx-string-symbol
          - --license
          - "CC-BY-NC-SA-4.0"
        language: system
        files: '\.(md|adoc)$'
        stages: [pre-commit]

      - id: reuse-shell
        name: REUSE annotate shell scripts
        entry: uv run --frozen --group dev reuse annotate
        args:
          - --copyright
          - "Caleb Cushing"
          - --merge-copyrights
          - --copyright-prefix
          - spdx-string-symbol
          - --license
          - "MIT"
          - --fallback-dot-license
          - --style
          - python
        language: system
        files: '(\.config/git/hooks/.*|.*\.sh)$'
        stages: [pre-commit]

      - id: reuse-properties
        name: REUSE annotate properties files
        entry: uv run --frozen --group dev reuse annotate
        args:
          - --copyright
          - "Caleb Cushing"
          - --merge-copyrights
          - --license
          - "CC0-1.0"
        language: system
        files: '\.properties$'
        stages: [pre-commit]

      - id: reuse-misc-config
        name: REUSE annotate misc config
        entry: uv run --frozen --group dev reuse annotate
        args:
          - --copyright
          - "Caleb Cushing"
          - --merge-copyrights
          - --license
          - "CC0-1.0"
          - --copyright-prefix
          - spdx-string-symbol
        language: system
        files: '\.(xml|yaml|properties|toml|json5)$'
        stages: [pre-commit]

      - id: reuse-scripts
        name: REUSE annotate scripts and workflows
        entry: uv run --frozen --group dev reuse annotate
        args:
          - --copyright
          - "Caleb Cushing"
          - --merge-copyrights
          - --copyright-prefix
          - spdx-string-symbol
          - --license
          - "MIT"
          - --fallback-dot-license
        language: system
        files: '\.(js|cjs|yml)$'
        stages: [pre-commit]

      - id: reuse-dotfiles
        name: REUSE annotate dotfiles
        entry: uv run --frozen --group dev reuse annotate
        args:
          - --copyright
          - "Caleb Cushing"
          - --merge-copyrights
          - --copyright-prefix
          - spdx-string-symbol
          - --license
          - "CC0-1.0"
        language: system
        files: '^\.(\*ignore|editorconfig|gitattributes|mailmap)$'
        stages: [pre-commit]
