#!/bin/sh

# SPDX-FileCopyrightText: Copyright © 2024 - 2025 Caleb Cushing
#
# SPDX-License-Identifier: MIT
[ -n "$CI" ] && exit 0

"$(dirname "$0")/check-yarn-env" || exit $?

yarn git-conventional-commits commit-msg-hook "$1"
