#!/bin/sh

# SPDX-FileCopyrightText: Copyright © 2026 Caleb Cushing
#
# SPDX-License-Identifier: MIT

# Skip in CI environments
[ -n "$CI" ] && exit 0

"$(dirname "$0")/check-yarn-env" || exit $?

yarn lint-staged
