# SPDX-FileCopyrightText: Copyright © 2024-2026 Caleb Cushing
#
# SPDX-License-Identifier: MIT

name: devtools-regression
on: push
permissions:
  contents: read
jobs:
  regression-prettier:
    uses: xenoterracide/github/.github/workflows/regression-devtool-prettier.yml@11700beacea8b4c946cbf47f1baf8bad55951747 # develop
  regression-git-conventional-commits:
    uses: xenoterracide/github/.github/workflows/regression-devtool-git-conventional-commits.yml@11700beacea8b4c946cbf47f1baf8bad55951747 # develop
  regression-pre-commit:
    uses: xenoterracide/github/.github/workflows/regression-devtool-pre-commit.yml@11700beacea8b4c946cbf47f1baf8bad55951747 # develop
  regression-reuse:
    uses: xenoterracide/github/.github/workflows/regression-devtool-reuse.yml@11700beacea8b4c946cbf47f1baf8bad55951747 # develop
  shell:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: actions/cache@v6.1.0
        with:
          path: ~/.asdf
          key: asdf-${{ runner.os }}-${{ hashFiles('.tool-versions') }}
          restore-keys: asdf-${{ runner.os }}-
      - uses: asdf-vm/actions/install@v4.0.1
      - run: shfmt --version
      - run: shellcheck --version
