# SPDX-FileCopyrightText: Copyright © 2024-2026 Caleb Cushing
#
# SPDX-License-Identifier: MIT
name: precommit
on: [push, workflow_call]
jobs:
  license:
    uses: xenoterracide/github/.github/workflows/license.yml@a188f0d095c96edd535338436f0ec6d8d5d4032f # develop
  prettier:
    uses: xenoterracide/github/.github/workflows/prettier.yml@a188f0d095c96edd535338436f0ec6d8d5d4032f # develop
  node-cli:
    uses: xenoterracide/github/.github/workflows/node-cli.yml@a188f0d095c96edd535338436f0ec6d8d5d4032f # develop
