# SPDX-FileCopyrightText: Copyright © 2024-2026 Caleb Cushing
#
# SPDX-License-Identifier: MIT

name: devtools-regression
on: push
permissions:
  contents: read
jobs:
  node-cli:
    uses: xenoterracide/github/.github/workflows/node-cli.yml@114ac59868ed0f45eada1a7c2acdc013a2159320 # develop
  shell:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6.0.3
      - uses: actions/cache@v5.0.5
        with:
          path: ~/.asdf
          key: asdf-${{ runner.os }}-${{ hashFiles('.tool-versions') }}
          restore-keys: asdf-${{ runner.os }}-
      - uses: asdf-vm/actions/install@v4.0.1
      - run: shfmt --version
      - run: shellcheck --version
