# SPDX-FileCopyrightText: Copyright © 2024-2026 Caleb Cushing
#
# SPDX-License-Identifier: MIT

name: pre-commit
on: push
permissions:
  contents: read
jobs:
  license:
    uses: xenoterracide/github/.github/workflows/license.yml@114ac59868ed0f45eada1a7c2acdc013a2159320 # develop
  prettier:
    uses: xenoterracide/github/.github/workflows/prettier.yml@114ac59868ed0f45eada1a7c2acdc013a2159320 # develop
  shfmt:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6.0.3
      - uses: actions/cache@v5.0.5
        with:
          path: ~/.asdf
          key: asdf-${{ runner.os }}-${{ hashFiles('.tool-versions') }}
          restore-keys: asdf-${{ runner.os }}-
      - uses: asdf-vm/actions/install@v4.0.1
      - run: shfmt -d git/hooks/
