# SPDX-FileCopyrightText: Copyright © 2024-2026 Caleb Cushing
#
# SPDX-License-Identifier: MIT

name: pre-commit
on: push
permissions:
  contents: read
jobs:
  license:
    uses: xenoterracide/github/.github/workflows/license.yml@8541abc4a3d38d099c3c9c4a381821b7438a6d98 # develop
  prettier:
    uses: xenoterracide/github/.github/workflows/prettier.yml@8541abc4a3d38d099c3c9c4a381821b7438a6d98 # develop
  shfmt:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6.0.3
      - uses: actions/cache@v6.1.0
        with:
          path: ~/.asdf
          key: asdf-${{ runner.os }}-${{ hashFiles('.tool-versions') }}
          restore-keys: asdf-${{ runner.os }}-
      - uses: asdf-vm/actions/install@v4.0.1
      - run: shfmt -d git/hooks/
