# SPDX-FileCopyrightText: Copyright © 2026 Caleb Cushing
#
# SPDX-License-Identifier: MIT

name: test
on: push
permissions:
  contents: read
jobs:
  node-cli:
    uses: xenoterracide/github/.github/workflows/node-cli.yml@8541abc4a3d38d099c3c9c4a381821b7438a6d98 # develop
  shell:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6.0.3
      - uses: asdf-vm/actions/install@v4.0.1
      - run: shellcheck git/hooks/*
